<?php

namespace App\Models;

use App\Models\Scopes\NewspaperScope;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Newspaper extends Model
{
    use HasFactory;
    use CrudTrait;

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new NewspaperScope());
    }

    protected $table = 'news';
    protected $guarded = ["id"];

    public function setSlugAttribute(): string
    {
        return $this->attributes["slug"] = "_";
    }
}
